apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 499656329194.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 499656329194.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: f929f181
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
